### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(SatoriManagerContent)
add_subdirectory(SatoriManager)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    SatoriManagerContentplugin
    SatoriManagerplugin)